name: Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  UbuntuTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ReleaseArtifact
        path: ./

    - name: 安装 .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Test
      working-directory: ${{github.workspace}}
      run: dotnet test UnitTest/bin/Release/net6.0/UnitTest.dll /logger:trx;LogFileName=UnitTestUbuntu.trx

    - uses: actions/upload-artifact@v2
      with:
        name: UbuntuTestResults
        path: |
            TestResults/**/*.*

    # 失败时我们收集一些信息，用于诊断
    - uses: actions/upload-artifact@v2
      name: UbuntuTestResults
      if: failure()
      with:
        name: ErrorLog
        path: |
            TestResults/**/*.*

